name: Build & Deploy Eurodle (gh-pages)

on:
  push:
    branches: [main]

permissions:
  contents: write      # necesario para crear gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
        working-directory: ./eurodle

      - run: npm run build
        working-directory: ./eurodle

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./eurodle/build
