name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./eurodle

      - name: Build project
        run: npm run build
        working-directory: ./eurodle

      - name: Deploy to GitHub Pages
        run: npm run deploy
        working-directory: ./eurodle
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
